apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website # 'matchLabels' is correct now
  template:        # 'template' field added
    metadata:
      labels:
        app: website
    spec:          # This 'spec' is for the Pod, nested under 'template'
      containers:
      - name: website
        image: kamlesh021/website:v1
        ports:
        - containerPort: 80
